DROP DATABASE IF EXISTS teste_estagio;
CREATE DATABASE teste_estagio;
USE teste_estagio;
CREATE TABLE posts
(
ID_Post INT(11) NOT NULL AUTO_INCREMENT,
AUTHOR VARCHAR(4) NOT NULL,
TITLE VARCHAR(20) NOT NULL,
TEXT VARCHAR(150) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
UPDATED_AT TIMESTAMP NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE comments
(
ID_Comments INT(11) NOT NULL AUTO_INCREMENT,
ID_Post INT(1) NOT NULL,
MESSAGE VARCHAR(150) NOT NULL,
AUTHOR VARCHAR(20) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
UPDATED_AT TIMESTAMP NOT NULL,
PRIMARY KEY(ID)
CONSTRAINT fk_poscom FOREIGN KEY (ID_Post) REFERENCES Pessoa (ID_Post)
);
